# version : "3.8"
# services :
#   web :
#      image : shiba07s/email-service-app:latest
#      ports :
#          - "3000:3000"
version: '3.8'

services:
  email-service:
    image: email-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   NODE_ENV: production
